### ISSUE TITLE
我对这个TG机器人有几个地方不太理解的想请教下

### ISSUE THREAD

**Issue by zhenhappy** [drakeet/DrakeetLoveBot#2]
1. 搭建这个机器人需要有公网的服务器不
2. 我@那个机器人father后获得了token，那么我的账号是不是就变成机器人了，还有我这个机器人能用在任何的群吗，还是说只有群主才能是机器人
3. 整个这个机器人的请求流程不是太明白他消息是如何传递的

**Comment by johnpoint** [comment]
1.需要
2.不是，能，不是
3.帮不了你

**Comment by drakeet** [comment]
@johnpoint 感谢帮忙回答。
